name: publish
on:
  release:
    types: [published]
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: install dotnet 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x      
        
      - name: install dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: install dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: build
        run: dotnet build

      - name: test
        run: dotnet test
        
      - name: publish Byndyusoft.Data.Relational.Abstractions
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Data.Relational.Abstractions/Byndyusoft.Data.Relational.Abstractions.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Data.Relational
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Data.Relational/Byndyusoft.Data.Relational.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
