name: publish
on:
  release:
    types: [published]
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: build
        run: dotnet build
        
      - name: publish Byndyusoft.Data.Relational.Abstractions
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Data.Relational.Abstractions/Byndyusoft.Data.Relational.Abstractions.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Data.Relational
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Data.Relational/Byndyusoft.Data.Relational.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Data.Relational.OpenTelemetry
        uses: alirezanet/publish-nuget@v3.0.0
        with:
          PROJECT_FILE_PATH: src/Byndyusoft.Data.Relational.OpenTelemetry/Byndyusoft.Data.Relational.OpenTelemetry.csproj
          VERSION_FILE_PATH: Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
